"""Output Assay local-validation scaffold."""

from assay.output_assay.analyzer import (
    OutputAssayAnalyzerScaffold,
    OutputAssayDraftValidationError,
    build_output_assay_extraction_failure,
    compute_output_assay_artifact_hash,
    output_assay_analysis_draft_schema,
    output_assay_analysis_draft_schema_errors,
    run_output_assay_locally,
    stamp_output_assay_run,
    validate_output_assay_analysis_draft,
)
from assay.output_assay.guardian import guardian_validate_output_assay_run
from assay.output_assay.models import (
    ArtifactSpanDraft,
    CompressionStatus,
    IntentClass,
    ObservationStatus,
    ObserverKind,
    OutputAssayAnalysisDraft,
    OutputAssayCompression,
    OutputAssayExtractionFailure,
    OutputAssayExtractionStage,
    OutputAssayGuardianVerdict,
    OutputAssayObservedUnit,
    OutputAssayObservedUnitDraft,
    OutputAssayObserver,
    OutputAssayPromotionEligibility,
    OutputAssayRunEnvelope,
    OutputAssayTruthVerification,
    PromotionEligibilityStatus,
    RunDisposition,
    SourceRole,
    TruthVerificationTier,
    UnitType,
)
from assay.output_assay.report import (
    OutputAssayFailOn,
    OutputAssayReportFormat,
    output_assay_result_status,
    render_output_assay_report,
    should_fail_output_assay_result,
)

__all__ = [
    "ArtifactSpanDraft",
    "CompressionStatus",
    "IntentClass",
    "ObservationStatus",
    "OutputAssayAnalysisDraft",
    "OutputAssayCompression",
    "OutputAssayExtractionFailure",
    "OutputAssayExtractionStage",
    "OutputAssayObservedUnit",
    "OutputAssayAnalyzerScaffold",
    "OutputAssayDraftValidationError",
    "OutputAssayObservedUnitDraft",
    "OutputAssayObserver",
    "OutputAssayPromotionEligibility",
    "OutputAssayRunEnvelope",
    "OutputAssayTruthVerification",
    "OutputAssayFailOn",
    "OutputAssayReportFormat",
    "ObserverKind",
    "PromotionEligibilityStatus",
    "SourceRole",
    "TruthVerificationTier",
    "UnitType",
    "build_output_assay_extraction_failure",
    "compute_output_assay_artifact_hash",
    "guardian_validate_output_assay_run",
    "output_assay_analysis_draft_schema",
    "output_assay_analysis_draft_schema_errors",
    "output_assay_result_status",
    "run_output_assay_locally",
    "render_output_assay_report",
    "should_fail_output_assay_result",
    "stamp_output_assay_run",
    "validate_output_assay_analysis_draft",
    "OutputAssayGuardianVerdict",
    "RunDisposition",
]
